# Generated by Django 4.0 on 2021-12-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('idBoard', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('cardId', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('listId', models.CharField(max_length=100)),
                ('idBoard', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('listId', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('idBoard', models.CharField(max_length=100)),
            ],
        ),
    ]
